### ISSUE TITLE
QT5 port

### ISSUE THREAD

**Issue by rickysarraf** [anilFree/seascope#30]
Hello Anil,

Are there plans to port seascope to Qt5 ?
In Debian, Qt4 libraries are slated for removal for the Buster cycle. A couple months ago, I did a port to Qt5, for one of my own projects and it was pretty straightforward.

Debian Bug report:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=875500

**Comment by anilFree** [comment]
now works with python3 + pyqt5
